spring.application.name=Pje-Migration

# Credenciais de acesso
app.usuario=MIGRADORPJE
app.senha=ip3w2r4y6i8

# Para conexão de banco de dados
spring.datasource.username=dbuser
spring.datasource.password=dbpassword
